[target.'cfg(target_os = "none")']
runner = "C:/Users/Killian/CLionProjects/Rust-Kernel/run.bat"

[build]
target = "x86_64-os.json"

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc"]